#pragma checksum "..\..\..\..\View\Pages\MainPage.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "42581C66489A5FA582DCAD24839479E0ED960C308A476CCBED6D23223210A68E"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WpfApp4.View.Pages;


namespace WpfApp4.View.Pages {
    
    
    /// <summary>
    /// MainPage
    /// </summary>
    public partial class MainPage : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 44 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask1;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask2;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask3;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask4;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask5;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask6;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask7;
        
        #line default
        #line hidden
        
        
        #line 143 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask8;
        
        #line default
        #line hidden
        
        
        #line 157 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask9;
        
        #line default
        #line hidden
        
        
        #line 177 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask10;
        
        #line default
        #line hidden
        
        
        #line 191 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask11;
        
        #line default
        #line hidden
        
        
        #line 205 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask12;
        
        #line default
        #line hidden
        
        
        #line 219 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask13;
        
        #line default
        #line hidden
        
        
        #line 233 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask14;
        
        #line default
        #line hidden
        
        
        #line 247 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask15;
        
        #line default
        #line hidden
        
        
        #line 261 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask16;
        
        #line default
        #line hidden
        
        
        #line 275 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask17;
        
        #line default
        #line hidden
        
        
        #line 295 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask18;
        
        #line default
        #line hidden
        
        
        #line 309 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask19;
        
        #line default
        #line hidden
        
        
        #line 323 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask20;
        
        #line default
        #line hidden
        
        
        #line 337 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask21;
        
        #line default
        #line hidden
        
        
        #line 351 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask22;
        
        #line default
        #line hidden
        
        
        #line 365 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask23;
        
        #line default
        #line hidden
        
        
        #line 379 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask24;
        
        #line default
        #line hidden
        
        
        #line 393 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask25;
        
        #line default
        #line hidden
        
        
        #line 412 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask26;
        
        #line default
        #line hidden
        
        
        #line 426 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask27;
        
        #line default
        #line hidden
        
        
        #line 440 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask28;
        
        #line default
        #line hidden
        
        
        #line 454 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask29;
        
        #line default
        #line hidden
        
        
        #line 468 "..\..\..\..\View\Pages\MainPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask30;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp4;component/view/pages/mainpage.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\View\Pages\MainPage.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.BtnTask1 = ((System.Windows.Controls.Button)(target));
            
            #line 45 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask1.Click += new System.Windows.RoutedEventHandler(this.BtnTask1_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.BtnTask2 = ((System.Windows.Controls.Button)(target));
            
            #line 60 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask2.Click += new System.Windows.RoutedEventHandler(this.BtnTask2_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.BtnTask3 = ((System.Windows.Controls.Button)(target));
            
            #line 74 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask3.Click += new System.Windows.RoutedEventHandler(this.BtnTask3_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.BtnTask4 = ((System.Windows.Controls.Button)(target));
            
            #line 88 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask4.Click += new System.Windows.RoutedEventHandler(this.BtnTask4_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.BtnTask5 = ((System.Windows.Controls.Button)(target));
            
            #line 102 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask5.Click += new System.Windows.RoutedEventHandler(this.BtnTask5_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.BtnTask6 = ((System.Windows.Controls.Button)(target));
            
            #line 116 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask6.Click += new System.Windows.RoutedEventHandler(this.BtnTask6_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.BtnTask7 = ((System.Windows.Controls.Button)(target));
            
            #line 130 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask7.Click += new System.Windows.RoutedEventHandler(this.BtnTask7_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.BtnTask8 = ((System.Windows.Controls.Button)(target));
            
            #line 144 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask8.Click += new System.Windows.RoutedEventHandler(this.BtnTask8_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.BtnTask9 = ((System.Windows.Controls.Button)(target));
            
            #line 158 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask9.Click += new System.Windows.RoutedEventHandler(this.BtnTask9_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.BtnTask10 = ((System.Windows.Controls.Button)(target));
            
            #line 178 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask10.Click += new System.Windows.RoutedEventHandler(this.BtnTask10_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.BtnTask11 = ((System.Windows.Controls.Button)(target));
            
            #line 192 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask11.Click += new System.Windows.RoutedEventHandler(this.BtnTask11_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.BtnTask12 = ((System.Windows.Controls.Button)(target));
            
            #line 206 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask12.Click += new System.Windows.RoutedEventHandler(this.BtnTask12_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.BtnTask13 = ((System.Windows.Controls.Button)(target));
            
            #line 220 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask13.Click += new System.Windows.RoutedEventHandler(this.BtnTask13_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.BtnTask14 = ((System.Windows.Controls.Button)(target));
            
            #line 234 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask14.Click += new System.Windows.RoutedEventHandler(this.BtnTask14_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.BtnTask15 = ((System.Windows.Controls.Button)(target));
            
            #line 248 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask15.Click += new System.Windows.RoutedEventHandler(this.BtnTask15_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.BtnTask16 = ((System.Windows.Controls.Button)(target));
            
            #line 262 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask16.Click += new System.Windows.RoutedEventHandler(this.BtnTask16_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.BtnTask17 = ((System.Windows.Controls.Button)(target));
            
            #line 276 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask17.Click += new System.Windows.RoutedEventHandler(this.BtnTask17_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.BtnTask18 = ((System.Windows.Controls.Button)(target));
            
            #line 296 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask18.Click += new System.Windows.RoutedEventHandler(this.BtnTask18_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.BtnTask19 = ((System.Windows.Controls.Button)(target));
            
            #line 310 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask19.Click += new System.Windows.RoutedEventHandler(this.BtnTask19_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.BtnTask20 = ((System.Windows.Controls.Button)(target));
            
            #line 324 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask20.Click += new System.Windows.RoutedEventHandler(this.BtnTask20_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.BtnTask21 = ((System.Windows.Controls.Button)(target));
            
            #line 338 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask21.Click += new System.Windows.RoutedEventHandler(this.BtnTask21_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.BtnTask22 = ((System.Windows.Controls.Button)(target));
            
            #line 352 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask22.Click += new System.Windows.RoutedEventHandler(this.BtnTask22_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.BtnTask23 = ((System.Windows.Controls.Button)(target));
            
            #line 366 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask23.Click += new System.Windows.RoutedEventHandler(this.BtnTask23_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.BtnTask24 = ((System.Windows.Controls.Button)(target));
            
            #line 380 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask24.Click += new System.Windows.RoutedEventHandler(this.BtnTask24_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.BtnTask25 = ((System.Windows.Controls.Button)(target));
            
            #line 394 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask25.Click += new System.Windows.RoutedEventHandler(this.BtnTask25_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            this.BtnTask26 = ((System.Windows.Controls.Button)(target));
            
            #line 413 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask26.Click += new System.Windows.RoutedEventHandler(this.BtnTask26_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            this.BtnTask27 = ((System.Windows.Controls.Button)(target));
            
            #line 427 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask27.Click += new System.Windows.RoutedEventHandler(this.BtnTask27_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.BtnTask28 = ((System.Windows.Controls.Button)(target));
            
            #line 441 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask28.Click += new System.Windows.RoutedEventHandler(this.BtnTask28_Click);
            
            #line default
            #line hidden
            return;
            case 29:
            this.BtnTask29 = ((System.Windows.Controls.Button)(target));
            
            #line 455 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask29.Click += new System.Windows.RoutedEventHandler(this.BtnTask29_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            this.BtnTask30 = ((System.Windows.Controls.Button)(target));
            
            #line 469 "..\..\..\..\View\Pages\MainPage.xaml"
            this.BtnTask30.Click += new System.Windows.RoutedEventHandler(this.BtnTask30_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

