#pragma checksum "..\..\..\..\View\Pages\Task1Page.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "66D2A4A0A2C39923DEEBF9108198158E62119C666FE17BC6641B6A14DCFD0F7A"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WpfApp4.View.Pages;


namespace WpfApp4.View.Pages {
    
    
    /// <summary>
    /// Task1Page
    /// </summary>
    public partial class Task1Page : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 30 "..\..\..\..\View\Pages\Task1Page.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnBack1;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\View\Pages\Task1Page.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTask2;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\View\Pages\Task1Page.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbY;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\View\Pages\Task1Page.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TbF;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\..\View\Pages\Task1Page.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAns;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\..\..\View\Pages\Task1Page.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TbG;
        
        #line default
        #line hidden
        
        
        #line 116 "..\..\..\..\View\Pages\Task1Page.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnOnMain;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp4;component/view/pages/task1page.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\View\Pages\Task1Page.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.BtnBack1 = ((System.Windows.Controls.Button)(target));
            
            #line 31 "..\..\..\..\View\Pages\Task1Page.xaml"
            this.BtnBack1.Click += new System.Windows.RoutedEventHandler(this.BtnBack1_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.BtnTask2 = ((System.Windows.Controls.Button)(target));
            
            #line 47 "..\..\..\..\View\Pages\Task1Page.xaml"
            this.BtnTask2.Click += new System.Windows.RoutedEventHandler(this.BtnTask2_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.TbY = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.TbF = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.BtnAns = ((System.Windows.Controls.Button)(target));
            
            #line 91 "..\..\..\..\View\Pages\Task1Page.xaml"
            this.BtnAns.Click += new System.Windows.RoutedEventHandler(this.BtnAns_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.TbG = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.BtnOnMain = ((System.Windows.Controls.Button)(target));
            
            #line 117 "..\..\..\..\View\Pages\Task1Page.xaml"
            this.BtnOnMain.Click += new System.Windows.RoutedEventHandler(this.BtnOnMain_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

